8c/app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, lm
from flask_login import UserMixin

class User(UserMixin, db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(16), index=True, unique=True)
	password_hash = db.Column(db.String(64))
	
	def set_password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	@staticmethod
	def register(username, password):
		user = User(username=username)
		user.set_password(password)
		db.session.add(user)
		db.session.commit()
		return user

	def __repr__(self):
		return '<User {0}>'.format(self.username)

@lm.user_loader
def load_user(id):
	return User.query.get(int(id))		

8c/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import Required, Length


class LoginForm(FlaskForm):
	username = StringField('Username', validators=[Required(), Length(1, 16)])
	password = PasswordField('Password', validators=[Required()])
	remember_me = BooleanField('Remember me')
	submit = SubmitField('Submit')

8c/app/__init__.py
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view = 'main.login'

def create_app(config_name):
	"""Create an application instance."""
	app = Flask(__name__)

	# import configuration
	cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
	app.config.from_pyfile(cfg)

	# initialize extensions
	bootstrap.init_app(app)
	db.init_app(app)
	lm.init_app(app)

	# import blueprints
	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	return app

8c/app/main/__init__.py
from flask import  Blueprint

main = Blueprint('main', __name__)

from . import routes

8c/app/main/routes.py
from flask import Flask, render_template, redirect, url_for, request
from flask_login import login_required, login_user, logout_user
from ..models import User
from . import main
from .forms import LoginForm


@main.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if user is None or not user.verify_password(form.password.data):
			return redirect(url_for('main.login', **request.args))
		login_user(user, form.remember_me.data)
		return redirect(request.args.get('next') or url_for('main.index'))
	return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
	logout_user()
	return redirect(url_for('main.index'))

@main.route('/')
def index():
	return render_template('index.html')

@main.route('/protected')
@login_required
def protected():
	return render_template('protected.html')

#@main.errorhandler(404)
#def not_found(e):
#	return render_template('404.html')

@main.route('/<path:invalid_path>')
def handle_unmatchable(*args, **kargs):
	return render_template('404.html')

8c/app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block navbar %}
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<a class="navbar-brand" href="{{ url_for('main.index') }}">The App</a>					
			<ul class="nav navbar-nav">
				<li><a href="{{ url_for('main.index') }}">Home</a></li>
				<li><a href="{{ url_for('main.protected') }}">Protected</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					{% if current_user.is_authenticated %}
						<a href="{{ url_for('main.logout') }}">Logout</a>
					{% else %}
						<a href="{{ url_for('main.login') }}">Login</a>
					{% endif %}
				</li>
			</ul>
		</div>
	</nav>
{% endblock %}

{% block content %}
	<div class="container">
		{% block page_content %}{% endblock %}
	</div>
{% endblock %}

8c/app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block page_content %}
	<h1>Home Page</h1>
	<p>This page can be viewed by all users.</p>
	<p>You are {% if not current_user.is_authenticated %}not {% endif %}logged in.</p>
{% endblock %}

8c/app/templates/login.html
{% extends "base.html" %}


{% block titile %}Login{% endblock %}

{% block page_content %}
	<h1>Login</h1>
	<div class="row">
		<div class="col-md-3">
			{{ wtf.quick_form(form) }}
		</div>
	</div>
{% endblock %}

8c/app/templates/protected.html
{% extends 'base.html' %}

{% block title %}Protected{% endblock %}

{% block page_content %}
	<h1>Protected Page</h1>
	<p>This page can be viewed by logged in users.</p>
	<p>You are logged in as <b>{{ current_user.username }}</b>.</p>
{% endblock %}